version: '3'

services:

  rsyslog:
    build: rsyslog
    ports:
     - 514:514
    networks:
     - rsyslog-apps

  app-go:
    build: app-go
    networks:
     - rsyslog-apps

networks:
  rsyslog-apps: