apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rsyslog
  labels:
    app: rsyslog
spec:
  selector:
    matchLabels:
      name: rsyslog
  template:
    metadata:
      labels:
        name: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: danielkraic/rsyslog:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: rsyslog-data
          mountPath: /var/run/rsyslog/dev/
          subPath: log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rsyslog-data
        hostPath:
          path: /rsyslog-data
          # TODO: add PVC?